version: '3.8'
services:
  dev-db:
    image: postgres:13
    environment:
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      POSTGRES_DB: dev
    ports:
      - 5434:5432
    volumes:
      - ./data/dev-db:/var/lib/postgresql/data
    restart: always
    networks:
      - myNet
networks:
  myNet:
